// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjPmJoWLCAN5cFeqtpKqPS4FFLSZJNT7k',
    appId: '1:593290488429:web:24ffba84b3835b9231ad64',
    messagingSenderId: '593290488429',
    projectId: 'quiz-app-ad3e0',
    authDomain: 'quiz-app-ad3e0.firebaseapp.com',
    storageBucket: 'quiz-app-ad3e0.appspot.com',
    measurementId: 'G-XMF3KK5C78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUCTQnagJpY170HDlAa82sEafzmRluRPc',
    appId: '1:593290488429:android:f031f37ea512f8a231ad64',
    messagingSenderId: '593290488429',
    projectId: 'quiz-app-ad3e0',
    storageBucket: 'quiz-app-ad3e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaBpNMVD0_2HFH1N4YH8gNjLi64dgR1yM',
    appId: '1:593290488429:ios:c0e173acb128807331ad64',
    messagingSenderId: '593290488429',
    projectId: 'quiz-app-ad3e0',
    storageBucket: 'quiz-app-ad3e0.appspot.com',
    iosClientId: '593290488429-g9g8iv2p000c42jo13th3j3j2maankgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaBpNMVD0_2HFH1N4YH8gNjLi64dgR1yM',
    appId: '1:593290488429:ios:c0e173acb128807331ad64',
    messagingSenderId: '593290488429',
    projectId: 'quiz-app-ad3e0',
    storageBucket: 'quiz-app-ad3e0.appspot.com',
    iosClientId: '593290488429-g9g8iv2p000c42jo13th3j3j2maankgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
